using Booking.Application.Appointments.Common.Interfaces;
using Booking.Application.Appointments.Dtos;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Booking.Infrastructure.Services
{

    public class PdfGenerator : IPdfGenerator
    {
        public byte[] GenerateMedicalReport(MedicalReportDto data)
        {
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(12).FontFamily("Arial"));

                    page.Header()
                        .Row(row =>
                        {
                            row.RelativeItem().Column(column =>
                            {
                                column.Item().Text("Medical Clinic 'Booking'").Bold().FontSize(20).FontColor(Colors.Blue.Medium);
                                column.Item().Text("Forchheim, Germany").FontSize(10);
                                column.Item().Text(DateTime.Now.ToShortDateString()).FontSize(10);
                            });

                        });

                    page.Content()
                        .PaddingVertical(1, Unit.Centimetre)
                        .Column(column =>
                        {
                            column.Item().Text("MEDICAL REPORT").FontSize(16).Bold().AlignCenter();
                            column.Item().PaddingBottom(10);

                            column.Item().Table(table =>
                            {
                                table.ColumnsDefinition(columns =>
                                {
                                    columns.ConstantColumn(100); 
                                    columns.RelativeColumn();    
                                });

                                table.Cell().Text("Doctor:").Bold();
                                table.Cell().Text($"{data.DoctorName} ({data.DoctorSpecialty})");

                                table.Cell().Text("Patient:").Bold();
                                table.Cell().Text(data.PatientName);

                                table.Cell().Text("Date:").Bold();
                                table.Cell().Text(data.Date.ToString("f"));
                            });

                            column.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                            column.Item().PaddingVertical(10);

                            column.Item().Text("Diagnosis & Notes:").Bold().FontSize(14);
                            column.Item().Text(data.Diagnosis);

                            column.Item().PaddingVertical(10);

                            column.Item().Text("Recommendations / Prescription:").Bold().FontSize(14);
                            column.Item().Text(data.Recommendations).Italic();
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text(x =>
                        {
                            x.Span("Generated by BookingSystem | Page ");
                            x.CurrentPageNumber();
                        });
                });
            });

            return document.GeneratePdf();
        }
    }
}